spring.application.name=nl-sql
# server config
server.port=8080

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/zoho_metadata
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
