# Server config
server.port=8080

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/zoho_metadata
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Zoho config
zoho.client.id=1000.2ZC8KDN7O5I8DF8Y3JYB4O9VOW4NZF
zoho.client.secret=e7036d3c47a031b6fa7ee7f6a233e346ceb032424d
zoho.refresh.token=1000.1262cfe6bd42eee240e9446a38855742.7198b652ddea6a93da0484fee669a292
zoho.org.id=60067461398
zoho.workspace.id=526255000000002004
zoho.view.id=526255000000004002